spring:

  devtools: 
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  # 개발할 때에만 create-drop 또는 update를 사용하고 운영 환경에서는 validate를 사용합니다.    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true        

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass

  mail:
    host: smtp.naver.com
    port: 465
    username: aaaa@naver.com
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          ssl:
            enable: true
            trust: smtp.naver.com

  mvc:
    hiddenmethod:      filter:        enabled: true

# 개발시 SQL 로깅을 하여 어떤 값으로 어떤 SQL이 실행되는지 확인합니다.
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
            
app:
  host: http://localhost:8080
  mailfrom: xxxx@naver.com      
  
         